const keyProperties = {
  Backquote: ['`', 'ё', '~', 'ё'],
  Digit1: ['1', '1', '!', '!'],
  Digit2: ['2', '2', '@', '"'],
  Digit3: ['3', '3', '#', '№'],
  Digit4: ['4', '4', '$', ';'],
  Digit5: ['5', '5', '%', '%'],
  Digit6: ['6', '6', '^', ':'],
  Digit7: ['7', '7', '&', '?'],
  Digit8: ['8', '8', '*', '*'],
  Digit9: ['9', '9', '(', '('],
  Digit0: ['0', '0', ')', ')'],
  Minus: ['-', '-', '_', '_'],
  Equal: ['=', '=', '+', '+'],
  Backspace: ['Backspace', 'Backspace', 'Backspace', 'Backspace'],
  Tab: ['Tab', 'Tab', 'Tab', 'Tab'],
  KeyQ: ['q', 'й', 'q', 'й'],
  KeyW: ['w', 'ц', 'w', 'ц'],
  KeyE: ['e', 'у', 'e', 'у'],
  KeyR: ['r', 'к', 'r', 'к'],
  KeyT: ['t', 'е', 't', 'е'],
  KeyY: ['y', 'н', 'y', 'н'],
  KeyU: ['u', 'г', 'u', 'г'],
  KeyI: ['i', 'ш', 'i', 'ш'],
  KeyO: ['o', 'щ', 'o', 'щ'],
  KeyP: ['p', 'з', 'p', 'з'],
  BracketLeft: ['[', 'х', '[', 'х'],
  BracketRight: [']', 'ъ', ']', 'ъ'],
  Backslash: ['\\', '\\', '|', '/'],
  Delete: ['Delete', 'Delete', 'Delete', 'Delete'],
  CapsLock: ['CapsLock', 'CapsLock', 'CapsLock', 'CapsLock'],
  KeyA: ['a', 'ф', 'a', 'ф'],
  KeyS: ['s', 'ы', 's', 'ы'],
  KeyD: ['d', 'в', 'd', 'в'],
  KeyF: ['f', 'а', 'f', 'а'],
  KeyG: ['g', 'п', 'g', 'п'],
  KeyH: ['h', 'р', 'h', 'р'],
  KeyJ: ['j', 'о', 'j', 'о'],
  KeyK: ['k', 'л', 'k', 'л'],
  KeyL: ['l', 'д', 'l', 'д'],
  Semicolon: [';', 'ж', ':', 'ж'],
  Quote: ["'", 'э', '"', 'э'],
  Enter: ['Enter', 'Enter', 'Enter', 'Enter'],
  ShiftLeft: ['Shift', 'Shift', 'Shift', 'Shift'],
  KeyZ: ['z', 'я', 'z', 'я'],
  KeyX: ['x', 'ч', 'x', 'ч'],
  KeyC: ['c', 'с', 'c', 'с'],
  KeyV: ['v', 'м', 'v', 'м'],
  KeyB: ['b', 'и', 'b', 'и'],
  KeyN: ['n', 'т', 'n', 'т'],
  KeyM: ['m', 'ь', 'm', 'ь'],
  Comma: [',', 'б', '<', 'б'],
  Period: ['.', 'ю', '>', 'ю'],
  Slash: ['/', '.', '?', ','],
  ArrowUp: ['&#8593;', '&#8593;', '&#8593;', '&#8593;'],
  ShiftRight: ['Shift', 'Shift', 'Shift', 'Shift'],
  ControlLeft: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
  MetaLeft: ['Win', 'Win', 'Win', 'Win'],
  AltLeft: ['Alt', 'Alt', 'Alt', 'Alt'],
  Space: [' ', ' ', ' ', ' '],
  AltRight: ['Alt', 'Alt', 'Alt', 'Alt'],
  ArrowLeft: ['&#8592;', '&#8592;', '&#8592;', '&#8592;'],
  ArrowDown: ['&#8595;', '&#8595;', '&#8595;', '&#8595;'],
  ArrowRight: ['&#8594;', '&#8594;', '&#8594;', '&#8594;'],
  ControlRight: ['Ctrl', 'Ctrl', 'Ctrl', 'Ctrl'],
};

const unhandleElements = [
  'Tab',
  'CapsLock',
  'ShiftLeft',
  'ControlLeft',
  'MetaLeft',
  'AltLeft',
  'AltRight',
  'ControlRight',
  'ShiftRight',
  'Enter',
  'Delete',
  'Backspace',
];
export { keyProperties, unhandleElements };
